<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <AnalysisLevel>latest</AnalysisLevel>
    </PropertyGroup>

    <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
        <PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers" />
    </ItemGroup>
</Project>
