// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XtreamForge.Database;

#nullable disable

namespace XtreamForge.Database.Migrations
{
    [DbContext(typeof(XtreamForgeDbContext))]
    [Migration("20261007185354_AddSeriesWatchHistory")]
    partial class AddSeriesWatchHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XtreamForge.Domain.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("case_sensitive");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operator");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pattern");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasKey("Id");

                    b.HasIndex("XtreamSourceId", "ContentType", "Sequence")
                        .IsUnique();

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.History.WatchHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "StartedAtUtc");

                    b.HasIndex("ContentType", "TmdbId");

                    b.ToTable("watch_history", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Items.ItemRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("case_sensitive");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operator");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pattern");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasKey("Id");

                    b.HasIndex("XtreamSourceId", "ContentType", "Sequence")
                        .IsUnique();

                    b.ToTable("item_rules", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Items.SeriesEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EpisodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("episode_id");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasKey("Id");

                    b.HasIndex("XtreamSourceId", "EpisodeId")
                        .IsUnique();

                    b.ToTable("series_episodes", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Items.StreamTmdbMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("LookupAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("lookup_attempt_count");

                    b.Property<DateTimeOffset?>("NextLookupAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_lookup_at_utc");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stream_id");

                    b.Property<long?>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasKey("Id");

                    b.HasIndex("XtreamSourceId", "ContentType", "StreamId")
                        .IsUnique();

                    b.ToTable("stream_tmdb_mappings", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Sources.XtreamSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("protocol");

                    b.HasKey("Id");

                    b.HasIndex("Protocol", "Host", "Port")
                        .IsUnique();

                    b.ToTable("xtream_sources", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Tmdb.TmdbInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Cast")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cast_members");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.PrimitiveCollection<List<string>>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("directors");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.PrimitiveCollection<List<int>>("GenreIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("genre_ids");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excluded");

                    b.Property<int>("LoadAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("load_attempt_count");

                    b.Property<DateTimeOffset?>("LoadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at_utc");

                    b.Property<DateTimeOffset>("NextLoadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_load_at_utc");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_path");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("vote_average");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_count");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "TmdbId")
                        .IsUnique();

                    b.ToTable("tmdb_infos", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Tmdb.TmdbRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("case_sensitive");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operator");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pattern");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "Sequence")
                        .IsUnique();

                    b.ToTable("tmdb_rules", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.CustomCategory", b =>
                {
                    b.HasBaseType("XtreamForge.Domain.Categories.Category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasIndex("ContentType", "Name")
                        .IsUnique();

                    b.ToTable("custom_categories", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.XtreamCategory", b =>
                {
                    b.HasBaseType("XtreamForge.Domain.Categories.Category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<int?>("CustomCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("custom_category_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excluded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("XtreamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("xtream_id");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasIndex("CustomCategoryId");

                    b.HasIndex("XtreamSourceId", "ContentType", "CustomCategoryId");

                    b.HasIndex("XtreamSourceId", "ContentType", "XtreamId")
                        .IsUnique();

                    b.ToTable("xtream_categories", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.CategoryRule", b =>
                {
                    b.HasOne("XtreamForge.Domain.Sources.XtreamSource", "XtreamSource")
                        .WithMany("CategoryRules")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Domain.Items.ItemRule", b =>
                {
                    b.HasOne("XtreamForge.Domain.Sources.XtreamSource", "XtreamSource")
                        .WithMany("ItemRules")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Domain.Items.SeriesEpisode", b =>
                {
                    b.HasOne("XtreamForge.Domain.Sources.XtreamSource", "XtreamSource")
                        .WithMany("SeriesEpisodes")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Domain.Items.StreamTmdbMapping", b =>
                {
                    b.HasOne("XtreamForge.Domain.Sources.XtreamSource", "XtreamSource")
                        .WithMany("StreamTmdbMappings")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.CustomCategory", b =>
                {
                    b.HasOne("XtreamForge.Domain.Categories.Category", null)
                        .WithOne()
                        .HasForeignKey("XtreamForge.Domain.Categories.CustomCategory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.XtreamCategory", b =>
                {
                    b.HasOne("XtreamForge.Domain.Categories.CustomCategory", "CustomCategory")
                        .WithMany("XtreamCategories")
                        .HasForeignKey("CustomCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XtreamForge.Domain.Categories.Category", null)
                        .WithOne()
                        .HasForeignKey("XtreamForge.Domain.Categories.XtreamCategory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XtreamForge.Domain.Sources.XtreamSource", "XtreamSource")
                        .WithMany("XtreamCategories")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomCategory");

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Domain.Sources.XtreamSource", b =>
                {
                    b.Navigation("CategoryRules");

                    b.Navigation("ItemRules");

                    b.Navigation("SeriesEpisodes");

                    b.Navigation("StreamTmdbMappings");

                    b.Navigation("XtreamCategories");
                });

            modelBuilder.Entity("XtreamForge.Domain.Categories.CustomCategory", b =>
                {
                    b.Navigation("XtreamCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
