// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XtreamForge.Infrastructure.Data;

#nullable disable

namespace XtreamForge.Infrastructure.Migrations
{
    [DbContext(typeof(XtreamForgeDbContext))]
    [Migration("20260911222029_AddXtreamCategoryManagement")]
    partial class AddXtreamCategoryManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.OutputCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsNameCustomized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_name_customized");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("XtreamForgeCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("xtreamforge_category_id");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasKey("Id");

                    b.HasIndex("XtreamSourceId", "ContentType", "SortOrder");

                    b.HasIndex("XtreamSourceId", "ContentType", "XtreamForgeCategoryId")
                        .IsUnique();

                    b.ToTable("output_categories", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.UpstreamCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<int>("DedicatedOutputCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("dedicated_output_category_id");

                    b.Property<DateTimeOffset>("FirstDiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_discovered_at_utc");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excluded");

                    b.Property<DateTimeOffset>("LastDiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_discovered_at_utc");

                    b.Property<int?>("OutputCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("output_category_id");

                    b.Property<string>("UpstreamCategoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("upstream_category_id");

                    b.Property<string>("UpstreamCategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("upstream_category_name");

                    b.Property<int>("XtreamSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("xtream_source_id");

                    b.HasKey("Id");

                    b.HasIndex("DedicatedOutputCategoryId");

                    b.HasIndex("OutputCategoryId");

                    b.HasIndex("XtreamSourceId", "ContentType", "OutputCategoryId");

                    b.HasIndex("XtreamSourceId", "ContentType", "UpstreamCategoryId")
                        .IsUnique();

                    b.ToTable("upstream_categories", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.XtreamSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("protocol");

                    b.HasKey("Id");

                    b.HasIndex("Protocol", "Host", "Port")
                        .IsUnique();

                    b.ToTable("xtream_sources", (string)null);
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.OutputCategory", b =>
                {
                    b.HasOne("XtreamForge.Infrastructure.Data.XtreamSource", "XtreamSource")
                        .WithMany("OutputCategories")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.UpstreamCategory", b =>
                {
                    b.HasOne("XtreamForge.Infrastructure.Data.OutputCategory", "DedicatedOutputCategory")
                        .WithMany("DedicatedUpstreamCategories")
                        .HasForeignKey("DedicatedOutputCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XtreamForge.Infrastructure.Data.OutputCategory", "OutputCategory")
                        .WithMany("MappedUpstreamCategories")
                        .HasForeignKey("OutputCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XtreamForge.Infrastructure.Data.XtreamSource", "XtreamSource")
                        .WithMany("UpstreamCategories")
                        .HasForeignKey("XtreamSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DedicatedOutputCategory");

                    b.Navigation("OutputCategory");

                    b.Navigation("XtreamSource");
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.OutputCategory", b =>
                {
                    b.Navigation("DedicatedUpstreamCategories");

                    b.Navigation("MappedUpstreamCategories");
                });

            modelBuilder.Entity("XtreamForge.Infrastructure.Data.XtreamSource", b =>
                {
                    b.Navigation("OutputCategories");

                    b.Navigation("UpstreamCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
