<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>21a896bc-b422-44e2-bb28-6627c91ec25d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\XtreamForge.ApiService\XtreamForge.ApiService.csproj" />
        <ProjectReference Include="..\XtreamForge.Web\XtreamForge.Web.csproj" />
    </ItemGroup>

</Project>
