<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\XtreamForge.Blazor\XtreamForge.Blazor.csproj" />
    <ProjectReference Include="..\XtreamForge\XtreamForge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>false</AspireUseCliBundle>
    <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
    <UserSecretsId>43b142a2-e885-4481-a4b3-c6118e8262b7</UserSecretsId>
  </PropertyGroup>

</Project>
